# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 619)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(400, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(50, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_start = QtWidgets.QPushButton(self.widget_2)
        self.btn_start.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet("#btn_start {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#btn_start:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_start:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        spacerItem1 = QtWidgets.QSpacerItem(100, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget_2, 3, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(122, 47, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setLineWidth(2)
        self.label_5.setMidLineWidth(2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(121, 47, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(408, 47, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(400, 50))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save_rows_xlsx = QtWidgets.QPushButton(self.widget_3)
        self.btn_save_rows_xlsx.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_rows_xlsx.setFont(font)
        self.btn_save_rows_xlsx.setStyleSheet("#btn_save_rows_xlsx {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius: 4px;\n"
"    padding: 0px 10px 0px 10px;\n"
"}\n"
"\n"
"#btn_save_rows_xlsx:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_save_rows_xlsx:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"")
        self.btn_save_rows_xlsx.setObjectName("btn_save_rows_xlsx")
        self.horizontalLayout_2.addWidget(self.btn_save_rows_xlsx)
        spacerItem5 = QtWidgets.QSpacerItem(100, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_save_file_xl = QtWidgets.QLabel(self.widget_3)
        self.label_save_file_xl.setText("")
        self.label_save_file_xl.setObjectName("label_save_file_xl")
        self.horizontalLayout_2.addWidget(self.label_save_file_xl)
        spacerItem6 = QtWidgets.QSpacerItem(100, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.label_finish = QtWidgets.QLabel(Form)
        self.label_finish.setText("")
        self.label_finish.setObjectName("label_finish")
        self.gridLayout.addWidget(self.label_finish, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setLineWidth(2)
        self.label_4.setMidLineWidth(2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_start.setText(_translate("Form", "Начать"))
        self.label_5.setText(_translate("Form", "Колонка"))
        self.lineEdit.setPlaceholderText(_translate("Form", "A"))
        self.btn_save_rows_xlsx.setText(_translate("Form", "Каталог для сохранения"))
        self.label_4.setText(_translate("Form", "Результат"))
