# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pages\admin\structure\UI_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(857, 601)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setMinimumSize(QtCore.QSize(400, 30))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_12 = QtWidgets.QWidget(Form)
        self.widget_12.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.comboBoxMethod = QtWidgets.QComboBox(self.widget_12)
        self.comboBoxMethod.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBoxMethod.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBoxMethod.setFont(font)
        self.comboBoxMethod.setObjectName("comboBoxMethod")
        self.horizontalLayout_2.addWidget(self.comboBoxMethod)
        spacerItem4 = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.comboBoxLang = QtWidgets.QComboBox(self.widget_12)
        self.comboBoxLang.setObjectName("comboBoxLang")
        self.comboBoxLang.addItem("")
        self.comboBoxLang.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxLang)
        spacerItem5 = QtWidgets.QSpacerItem(400, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addWidget(self.widget_14)
        self.verticalLayout.addWidget(self.widget_12)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(400, 30))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.btn_generate = QtWidgets.QPushButton(self.widget_3)
        self.btn_generate.setMinimumSize(QtCore.QSize(130, 30))
        self.btn_generate.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_generate.setFont(font)
        self.btn_generate.setStyleSheet("#btn_generate {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#btn_generate:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_generate:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sync_w.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_generate.setIcon(icon)
        self.btn_generate.setObjectName("btn_generate")
        self.horizontalLayout_6.addWidget(self.btn_generate)
        spacerItem7 = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setMinimumSize(QtCore.QSize(300, 30))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.message = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.message.setFont(font)
        self.message.setText("")
        self.message.setObjectName("message")
        self.horizontalLayout.addWidget(self.message)
        spacerItem9 = QtWidgets.QSpacerItem(500, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.widget_5)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Метод сборки"))
        self.label_2.setText(_translate("Form", "Язык"))
        self.comboBoxLang.setItemText(0, _translate("Form", "uk"))
        self.comboBoxLang.setItemText(1, _translate("Form", "ru"))
        self.btn_generate.setText(_translate("Form", "Сгенерировать"))

