# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pages\api\api_update_cards\UI_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 678)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_ids = QtWidgets.QTextEdit(Form)
        self.textEdit_ids.setObjectName("textEdit_ids")
        self.gridLayout.addWidget(self.textEdit_ids, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 80))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_request = QtWidgets.QPushButton(self.widget)
        self.btn_request.setMinimumSize(QtCore.QSize(180, 30))
        self.btn_request.setMaximumSize(QtCore.QSize(220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.btn_request.setFont(font)
        self.btn_request.setStyleSheet("#btn_request {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"#btn_request:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_request:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sync_w.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_request.setIcon(icon)
        self.btn_request.setIconSize(QtCore.QSize(18, 18))
        self.btn_request.setObjectName("btn_request")
        self.horizontalLayout_4.addWidget(self.btn_request)
        spacerItem1 = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.textEdit_res = QtWidgets.QTextEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_res.setFont(font)
        self.textEdit_res.setObjectName("textEdit_res")
        self.gridLayout.addWidget(self.textEdit_res, 4, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setMinimumSize(QtCore.QSize(400, 40))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(50, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setMinimumSize(QtCore.QSize(200, 30))
        self.label_9.setMaximumSize(QtCore.QSize(310, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setMinimumSize(QtCore.QSize(140, 30))
        self.label_7.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget_6, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_request.setText(_translate("Form", "Получить "))
        self.textEdit_res.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("Form", "Введите ID карточки (каждый на новой строке)"))
        self.label_7.setText(_translate("Form", "Результат ответа"))
