# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pages\api\api_upload_videos\UI_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(825, 916)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableVideo = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableVideo.setFont(font)
        self.tableVideo.setGridStyle(QtCore.Qt.NoPen)
        self.tableVideo.setRowCount(1)
        self.tableVideo.setColumnCount(2)
        self.tableVideo.setObjectName("tableVideo")
        item = QtWidgets.QTableWidgetItem()
        self.tableVideo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVideo.setHorizontalHeaderItem(1, item)
        self.tableVideo.horizontalHeader().setDefaultSectionSize(197)
        self.tableVideo.verticalHeader().setDefaultSectionSize(24)
        self.gridLayout_2.addWidget(self.tableVideo, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(296, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_request = QtWidgets.QPushButton(self.widget)
        self.btn_request.setMinimumSize(QtCore.QSize(180, 30))
        self.btn_request.setMaximumSize(QtCore.QSize(220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_request.setFont(font)
        self.btn_request.setStyleSheet("#btn_request {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"#btn_request:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_request:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sync_w.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_request.setIcon(icon)
        self.btn_request.setIconSize(QtCore.QSize(18, 18))
        self.btn_request.setObjectName("btn_request")
        self.horizontalLayout.addWidget(self.btn_request)
        spacerItem1 = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(316, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setMinimumSize(QtCore.QSize(140, 30))
        self.label_7.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 2, 0, 1, 1)
        self.tableResult = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableResult.setFont(font)
        self.tableResult.setGridStyle(QtCore.Qt.NoPen)
        self.tableResult.setRowCount(1)
        self.tableResult.setColumnCount(4)
        self.tableResult.setObjectName("tableResult")
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(3, item)
        self.tableResult.horizontalHeader().setDefaultSectionSize(197)
        self.tableResult.verticalHeader().setDefaultSectionSize(24)
        self.gridLayout_2.addWidget(self.tableResult, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableVideo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableVideo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Url"))
        self.btn_request.setText(_translate("Form", "Получить "))
        self.label_7.setText(_translate("Form", "Результат ответа"))
        item = self.tableResult.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableResult.horizontalHeaderItem(1)
        item.setText(_translate("Form", "URL"))
        item = self.tableResult.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Code"))
        item = self.tableResult.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Status"))
