# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pages\api\api_get_filters\UI_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 678)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(197)
        self.tableWidget.verticalHeader().setDefaultSectionSize(24)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setMinimumSize(QtCore.QSize(140, 30))
        self.label_7.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget_6, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(200, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.translate_url = QtWidgets.QFrame(self.frame_2)
        self.translate_url.setMinimumSize(QtCore.QSize(300, 30))
        self.translate_url.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.translate_url.setFont(font)
        self.translate_url.setStyleSheet("#translate_url {\n"
"    border:  1px solid #aa7e6f;\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.translate_url.setFrameShape(QtWidgets.QFrame.Box)
        self.translate_url.setFrameShadow(QtWidgets.QFrame.Raised)
        self.translate_url.setObjectName("translate_url")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.translate_url)
        self.horizontalLayout_13.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.category_slug = QtWidgets.QLineEdit(self.translate_url)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.category_slug.setFont(font)
        self.category_slug.setText("")
        self.category_slug.setFrame(False)
        self.category_slug.setClearButtonEnabled(True)
        self.category_slug.setObjectName("category_slug")
        self.horizontalLayout_13.addWidget(self.category_slug)
        self.horizontalLayout_6.addWidget(self.translate_url)
        spacerItem3 = QtWidgets.QSpacerItem(200, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 80))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btn_request = QtWidgets.QPushButton(self.widget)
        self.btn_request.setMinimumSize(QtCore.QSize(180, 30))
        self.btn_request.setMaximumSize(QtCore.QSize(220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.btn_request.setFont(font)
        self.btn_request.setStyleSheet("#btn_request {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"#btn_request:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_request:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sync_w.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_request.setIcon(icon)
        self.btn_request.setIconSize(QtCore.QSize(18, 18))
        self.btn_request.setObjectName("btn_request")
        self.horizontalLayout_4.addWidget(self.btn_request)
        spacerItem5 = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.label_audio = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_audio.setFont(font)
        self.label_audio.setObjectName("label_audio")
        self.horizontalLayout_7.addWidget(self.label_audio)
        spacerItem7 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "FilterGroup"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "FilterName"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "FilterURL"))
        self.label_7.setText(_translate("Form", "Результат ответа"))
        self.category_slug.setPlaceholderText(_translate("Form", "planshety"))
        self.btn_request.setText(_translate("Form", "Получить "))
        self.label_audio.setText(_translate("Form", "slug категории"))
