# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(782, 632)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_generate_table = QtWidgets.QPushButton(self.widget)
        self.btn_generate_table.setMinimumSize(QtCore.QSize(140, 30))
        self.btn_generate_table.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_generate_table.setFont(font)
        self.btn_generate_table.setStyleSheet("#btn_generate_table {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"#btn_generate_table:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_generate_table:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sync_w.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_generate_table.setIcon(icon)
        self.btn_generate_table.setIconSize(QtCore.QSize(18, 18))
        self.btn_generate_table.setObjectName("btn_generate_table")
        self.horizontalLayout_4.addWidget(self.btn_generate_table)
        spacerItem1 = QtWidgets.QSpacerItem(300, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget, 4, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(Form)
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 70)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(240, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_save_file_xl = QtWidgets.QLabel(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_save_file_xl.sizePolicy().hasHeightForWidth())
        self.label_save_file_xl.setSizePolicy(sizePolicy)
        self.label_save_file_xl.setMinimumSize(QtCore.QSize(300, 30))
        self.label_save_file_xl.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_save_file_xl.setFont(font)
        self.label_save_file_xl.setText("")
        self.label_save_file_xl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_save_file_xl.setObjectName("label_save_file_xl")
        self.horizontalLayout_7.addWidget(self.label_save_file_xl)
        spacerItem3 = QtWidgets.QSpacerItem(230, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.gridLayout.addWidget(self.widget_9, 5, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_save = QtWidgets.QLineEdit(self.widget_5)
        self.line_save.setEnabled(True)
        self.line_save.setMinimumSize(QtCore.QSize(250, 30))
        self.line_save.setMaximumSize(QtCore.QSize(1500, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.line_save.setFont(font)
        self.line_save.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.line_save.setAcceptDrops(True)
        self.line_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_save.setStyleSheet("border: 1px solid #edeef0;\n"
"padding-left: 4px;\n"
"border-radius: 4px;")
        self.line_save.setText("")
        self.line_save.setMaxLength(100)
        self.line_save.setFrame(True)
        self.line_save.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_save.setCursorPosition(0)
        self.line_save.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_save.setDragEnabled(False)
        self.line_save.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.line_save.setClearButtonEnabled(False)
        self.line_save.setObjectName("line_save")
        self.verticalLayout_2.addWidget(self.line_save)
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_select = QtWidgets.QPushButton(self.widget_7)
        self.btn_select.setEnabled(True)
        self.btn_select.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_select.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_select.setFont(font)
        self.btn_select.setStyleSheet("#btn_select {\n"
"    background-color:#065fd4;\n"
"    color: #fff;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"#btn_select:hover {\n"
"    color: #fff;\n"
"    background-color:#002ead;\n"
"    box-shadow: 0px 0px 2px 2px rgb(0,0,0);\n"
"    transition: 0.7s;\n"
"}\n"
"\n"
"#btn_select:pressed {\n"
"    border: 4px solid #065fd4;\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/folder_open_w.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_select.setIcon(icon1)
        self.btn_select.setIconSize(QtCore.QSize(18, 18))
        self.btn_select.setFlat(False)
        self.btn_select.setObjectName("btn_select")
        self.verticalLayout.addWidget(self.btn_select)
        self.horizontalLayout.addWidget(self.widget_7)
        self.gridLayout.addWidget(self.widget_4, 3, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(Form)
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(240, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(300, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(230, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget_10, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setMinimumSize(QtCore.QSize(400, 30))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(70, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btn_open_xlsx = QtWidgets.QPushButton(self.widget_6)
        self.btn_open_xlsx.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_open_xlsx.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_xlsx.setFont(font)
        self.btn_open_xlsx.setStyleSheet("#btn_open_xlsx {\n"
"    background-color:#198754;\n"
"    color: #fff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#btn_open_xlsx:hover {\n"
"    color: #fff;\n"
"    background-color:#157347;\n"
"}\n"
"\n"
"#btn_open_xlsx:pressed {\n"
"    border: 4px solid #9dccb6;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/file-xlsx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_xlsx.setIcon(icon2)
        self.btn_open_xlsx.setObjectName("btn_open_xlsx")
        self.horizontalLayout_3.addWidget(self.btn_open_xlsx)
        spacerItem7 = QtWidgets.QSpacerItem(70, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.gridLayout.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(240, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.label_open_file_xl = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_open_file_xl.sizePolicy().hasHeightForWidth())
        self.label_open_file_xl.setSizePolicy(sizePolicy)
        self.label_open_file_xl.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_open_file_xl.setFont(font)
        self.label_open_file_xl.setText("")
        self.label_open_file_xl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_open_file_xl.setObjectName("label_open_file_xl")
        self.horizontalLayout_8.addWidget(self.label_open_file_xl)
        spacerItem9 = QtWidgets.QSpacerItem(230, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_generate_table.setText(_translate("Form", "Сгенерировать"))
        self.line_save.setPlaceholderText(_translate("Form", " Укажите каталог для сохранения"))
        self.btn_select.setText(_translate("Form", "Выбрать"))
        self.btn_open_xlsx.setText(_translate("Form", "Открыть"))
        